### ISSUE TITLE
Fatal error 

### ISSUE THREAD

**Issue by camlafit** [acmephp/acmephp#203]
Hello

After installed phar file as explained on [documentation](https://acmephp.github.io/documentation/getting-started/1-installation.html) and test my first config file I get this errror :
```
PHP Fatal error:  Uncaught Error: Class 'League\Flysystem\Memory\MemoryAdapter' not found in phar:///root/acmephp.phar/src/Core/Filesystem/Adapter/NullAdapter.php:21
Stack trace:
#0 phar:///root/acmephp.phar/src/Core/Challenge/Http/FilesystemSolver.php(54): AcmePhp\Core\Filesystem\Adapter\NullAdapter->__construct()
#1 [internal function]: AcmePhp\Core\Challenge\Http\FilesystemSolver->__construct(Object(Symfony\Component\DependencyInjection\ServiceLocator), Object(AcmePhp\Core\Challenge\Http\HttpDataExtractor))
#2 phar:///root/acmephp.phar/vendor/symfony/dependency-injection/ContainerBuilder.php(1169): ReflectionClass->newInstanceArgs(Array)
#3 phar:///root/acmephp.phar/vendor/symfony/dependency-injection/ContainerBuilder.php(633): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, false, 'acmephp.challen...')
#4 phar:///root/acmephp.phar/vendor/symfony/dependency-injection/ContainerBuilder.php(1274): Symfony\Component\DependencyInjection\Contai in phar:///root/acmephp.phar/src/Core/Filesystem/Adapter/NullAdapter.php on line 21
```

With latest version this error doesn't occur.

**Comment by tgalopin** [comment]
Hello!

Thanks for the heads up, I'm going to have a look and release a new version in the coming days.

**Comment by camlafit** [comment]
Hello

Any update about this ?

Thanks

**Comment by camlafit** [comment]
As latest version from looks ok https://acmephp.github.io/documentation/getting-started/1-installation.html

Could be nice to update files as I've seen a 2.1.0 in releases list :)

**Comment by SamMousa** [comment]
Closing this due to old age.
